### ISSUE TITLE
Which one is it?

### ISSUE THREAD

**Issue by osangni101020** [RMNCLDYO/perplexity-ai-toolkit#3]
is it the https://labs.perplexity.ai/

or the main perplexity site?

**Comment by RMNCLDYO** [comment]
Sorry, I'm not sure I understand your question. Could you please clarify?

**Comment by osangni101020** [comment]
https://labs.perplexity.ai/

is is a wrapper for this?

**Comment by ramonclaudio** [comment]
> https://labs.perplexity.ai/
> 
> is is a wrapper for this?

This toolkit is a wrapper and command-line interface for the Perplexity REST API. We do not control the Perplexity front-end. Please refer to the official perplexity forum [here](https://github.com/ppl-ai/api-discussion/discussions) with any inquiries.
