### ISSUE TITLE
Automatic Scroll Issue After Generating Answer

### ISSUE THREAD

**Issue by a1n13a1n13d4** [RMNCLDYO/perplexity-ai-toolkit#4]
Here is the corrected bug report:

**Desktop (please complete the following information):**
- OS: Windows 11
- Browser: MS Edge (Microsoft Edge)
- Version: 109.0

**Description about bug:**
When Perplexity AI generates an answer for a solution, after the solution ends, the screen automatically scrolls up a little bit, but it does not come above the top of the screen. This issue is observed on the Perplexity webpage 'https://www.perplexity.ai/search/'.

**Steps to Reproduce:**

1. Go to 'https://www.perplexity.ai/search/'
2. Enter a query or prompt and generate an answer.
3. Observe the screen when the answer generation is complete. You will see the bug.

**Expected behavior:**
The screen should remain stationary and not scroll up or down automatically.

**Actual Behavior:**
The screen scrolls up a little bit after the answer is generated.

**Desktop (please complete the following information):**
- OS: Windows 11
- Browser: MS Edge (Microsoft Edge)
- Version: 109.0

**Additional context:**
I have not used this AI on my phone recently, but in the past, I did not encounter this issue in time of used that.

**Comment by ramonclaudio** [comment]
This toolkit is a wrapper and command-line interface for the Perplexity REST API. We do not control the Perplexity front-end. Please refer to the official perplexity forum [here](https://github.com/ppl-ai/api-discussion/discussions) with any inquiries.
